### ISSUE TITLE
Uploading to sharepoint fails with Call to a member function getFileName() on string

### ISSUE THREAD

**Issue by tdondich** [bitsnbolts/flysystem-sharepoint#1]
When attempting to upload to sharepoint, the addFileToList method gets called on the SharepointAdapter.  The $upload parameter is actually a string.  But the method attempts to call getFileName on it.

I'll build a PR to correct the issue for you.

Great initial project by the way!

**Comment by thijsvdanker** [comment]
Hi @tdondich,

My implementation was/is a little bit to tightly coupled to my own usage; thanks for jumping in and improving it!

**Comment by thijsvdanker** [comment]
I did re-add the escaping of single quotes in the filename in https://github.com/thijsvdanker/flysystem-sharepoint/commit/50142deeadca20a1fc9a2671461db3af89cbba50. As searching for the file with
```php
$items->filter('Name eq \'' . $filename . '\'')->top(1);
```
would otherwise fail.
